[tool.poetry]
name = "CokkieBot"
version = "0.1.0"
description = "TEST"
authors = ["CokkieYT","pdf114514"]

[tool.poetry.dependencies]
python = "^3.7"
fortnitepy = "^3.3.0"
"discord.py" = "^1.4.2"
requests = "^2.24.0"
crayons = "^0.3.1"
jaconv = "^0.2.4"
Jinja2 = "^2.11.2"
sanic = "^20.6.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
